#PostreSQL
server:
  port: 8888

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/zadanie
    username: zadanie
    password: almarwinnet
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    sql: debug




